apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service-db-vn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-service-db-vn
  template:
    metadata:
      labels:
        app: trip-service-db-vn
    spec:
      containers:
        - name: trip-service-db-vn
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "trip_service_db"
            - name: POSTGRES_USER
              value: "trip_service_user"
            - name: POSTGRES_PASSWORD
              value: "trip_service_pass"
          volumeMounts:
            - name: trip-db-vn-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: trip-db-vn-data
          persistentVolumeClaim:
            claimName: infra_trip_db_vn_data
