spring:
  application:
    name: trip-service
  datasource:
    url: jdbc:postgresql://trip-service-db:5432/trip_service_db
    username: trip_service_user
    password: trip_service_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
