spring:
  application:
    name: trip-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/trip_service_db
    username: ${DB_USERNAME:trip_service_user}
    password: ${DB_PASSWORD:trip_service_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

user:
  grpc:
    service:
      url: user-grpc-service:50051