spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-service-db:5432/user_service_db
    username: user_service_user
    password: user_service_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Change from 'update' to 'validate' 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
