version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - microservices-network

  user-service:
    build: ../backend/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - user-service-db
    networks:
      - microservices-network

  trip-service:
    build: ../backend/trip-service
    container_name: trip-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - trip-service-db
    networks:
      - microservices-network

  driver-service:
    build: ../backend/driver-service
    container_name: driver-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - redis   # ✔ driver-service cần redis
    networks:
      - microservices-network

  driver-simulator:
    build: ../backend/driver-simulator
    container_name: driver-simulator
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - driver-service   # ✔ simulator cần driver-service
    networks:
      - microservices-network

  user-service-db:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: user_service_pass
    ports:
      - "5435:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  trip-service-db:
    image: postgres:15
    container_name: trip-service-db
    environment:
      POSTGRES_DB: trip_service_db
      POSTGRES_USER: trip_service_user
      POSTGRES_PASSWORD: trip_service_pass
    ports:
      - "5433:5432"
    volumes:
      - trip_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

volumes:
  user_db_data:
  trip_db_data:
  redis-data:

networks:
  microservices-network:
    driver: bridge
