spring:
  application:
    name: driver-service

  datasource:
    url: jdbc:postgresql://driver-service-db:5432/driver_service_db
    username: driver_service_user
    password: driver_service_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    redis:
      host: redis
      port: 6379

grpc:
  server:
    port: 9092

server:
  port: 8083

