spring:
  datasource:
    url: jdbc:postgresql://driver-service-db:5432/driver_service_db
    username: ${spring.datasource.username:postgres}
    password: ${spring.datasource.password:postgres}
  data:
    redis:
      host: ${spring.redis.host:redis}
      port: ${spring.redis.port:6379}
      client-type: jedis
      jedis:
        pool:
          max-active: 128
          max-idle: 128
          min-idle: 16
          max-wait: -1ms

  session:
    store-type: redis
    redis:
      namespace: spring:session

  rabbitmq:
    host: ${spring.rabbitmq.host:rabbitmq}
    port: ${spring.rabbitmq.port:5672}
    username: ${spring.rabbitmq.username:guest}
    password: ${spring.rabbitmq.password:guest}
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10

grpc:
  server:
    port: 9003
    enable-keep-alive: true
    keep-alive-time: 30s
    keep-alive-timeout: 10s

server:
  port: 8083
  servlet:
    context-path: /api/driver-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
