apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-grpc
  template:
    metadata:
      labels:
        app: driver-grpc
    spec:
      containers:
        - name: driver-grpc
          image: uit-go/driver-grpc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50053
