apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-grpc
  template:
    metadata:
      labels:
        app: trip-grpc
    spec:
      containers:
        - name: trip-grpc
          image: trip-grpc:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50052
