apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-grpc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-grpc-service
  template:
    metadata:
      labels:
        app: trip-grpc-service
    spec:
      containers:
        - name: trip-grpc-service
          image: uit-go/trip-grpc-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50052
