apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-grpc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-grpc-service
  template:
    metadata:
      labels:
        app: user-grpc-service
    spec:
      containers:
        - name: user-grpc-service
          image: uit-go/user-grpc-service:latest
          ports:
            - containerPort: 50051
