apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-grpc
  template:
    metadata:
      labels:
        app: user-grpc
    spec:
      containers:
        - name: user-grpc
          image: uit-go/user-grpc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
