apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trip-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trip-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
    # Use ContainerResource to target specific container (ignore linkerd-proxy)
    - type: ContainerResource
      containerResource:
        name: cpu
        container: trip-service
        target:
          type: Utilization
          averageUtilization: 70
    - type: ContainerResource
      containerResource:
        name: memory
        container: trip-service
        target:
          type: Utilization
          averageUtilization: 80